# For more information: https://laravel.com/docs/sail
version: '3'

services:
  laravel:
    image: thecodingmachine/php:8.0-v4-apache
    ports:
        - '${APP_PORT:-8080}:80'
    environment:
        PHP_EXTENSIONS: bcmath gd intl pdo_pgsql pgsql
        PHP_INI_MEMORY_LIMIT: 512M
        PHP_INI_DATE__TIMEZONE: Asia/Tokyo
        PHP_INI_MBSTRING__LANGUAGE: Japanese
        APACHE_DOCUMENT_ROOT: /var/www/html/public
    volumes:
        - '.:/var/www/html'
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_DATABASE: '${DB_DATABASE:-db}'
      MYSQL_USER: '${DB_USERNAME:-sail}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$a{DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s
  mail:
    image: mailhog/mailhog
    ports:
      - '${MAIL_HOG_PORT:-8025}:8025'